version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g npm@9.8.1
  pre_build:
    commands:
      - npm install --legacy-peer-deps
      - echo "REACT_APP_FAST_API_URL=${REACT_APP_FAST_API_URL}" >> .env
      - echo "REACT_APP_SPRING_API_URL=${REACT_APP_SPRING_API_URL}" >> .env
      - echo "REACT_APP_S3_BUCKET=${REACT_APP_S3_BUCKET}" >> .env
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build