version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g npm@9.8.1
  pre_build:
    commands:
      - npm install --legacy-peer-deps
  build:
    commands:
      # 환경 변수 주입
      - export REACT_APP_FAST_API_URL=$REACT_APP_FAST_API_URL
      - export REACT_APP_SPRING_API_URL=$REACT_APP_SPRING_API_URL
      - export REACT_APP_S3_BUCKET=$REACT_APP_S3_BUCKET

      # React 앱 빌드
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
